# Generated by Django 2.1.3 on 2018-12-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('author_intro', models.TextField()),
                ('rating', models.CharField(max_length=5)),
                ('publisher', models.CharField(max_length=100)),
                ('pubdate', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=500)),
                ('pages', models.CharField(max_length=10)),
                ('binding', models.CharField(max_length=50)),
                ('image_s', models.CharField(max_length=100)),
                ('image_m', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndexSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', models.CharField(max_length=50)),
                ('big_image', models.CharField(max_length=50)),
                ('small_image', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('search_pages', models.IntegerField()),
                ('search_pages_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('W', 'WAIT_DEAL'), ('F', 'FINISHED')], max_length=1)),
                ('contain', models.ManyToManyField(to='bookstore.Books')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('chart', models.ManyToManyField(to='bookstore.Books')),
            ],
        ),
    ]
