# Generated by Django 2.1.3 on 2018-12-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20181219_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', '等待确认'), ('F', '已完成')], max_length=1),
        ),
    ]
