# Generated by Django 2.1.3 on 2018-12-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20181219_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', '等待客户支付'), ('W', '等待确认'), ('F', '已完成')], max_length=1),
        ),
    ]
