# Generated by Django 2.1.3 on 2018-12-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20181220_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
