# Generated by Django 2.1.3 on 2018-12-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_order_pi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pi',
        ),
        migrations.AddField(
            model_name='order',
            name='order_oi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
