# Generated by Django 2.1.3 on 2018-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20181220_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
