# Generated by Django 2.1.3 on 2018-12-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_order_order_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
