# Generated by Django 2.1.3 on 2018-12-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_order_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', '等待客户支付'), ('W', '支付完成，等待店主发货'), ('F', '已发货，请注意接收')], max_length=1),
        ),
    ]
