# Generated by Django 2.1.3 on 2018-12-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20181224_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repeal_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', '等待客户支付'), ('W', '支付完成，等待店主发货'), ('F', '已发货，请注意接收'), ('R', '商家撤销了订单！')], max_length=1),
        ),
    ]
